# Generated by Django 4.1.4 on 2023-01-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placementdata', '0001_initial'),
        ('placement_course_wise_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementbranchdata',
            name='placement_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_wise', to='placementdata.placementdata'),
        ),
    ]
