# Generated by Django 4.1.4 on 2023-01-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
        ('placementdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placementdata',
            unique_together={('calendar',)},
        ),
    ]
